### ISSUE TITLE
[BUG] - Problem importing contentType with dynamicZone

### ISSUE THREAD

**Issue by Charlesdoiron** [Baboo7/strapi-plugin-import-export-entries#16]
**Describe the bug**
Hello !
I have a contentType with a dynamicZone.
In the dynamicZone i have a repeatable component.

I can export the contentType but i can't import it. 

**To Reproduce**
Got to the contentType Menu.
Export one Menu in Json.
Change the title.
Import the same Json (with title modified).
Get the error `"error": "Cannot read properties of undefined (reading 'attributes')"`

`TypeError: Cannot read properties of undefined (reading 'attributes')
    at getModelAttributes (/Users/charlesdoiron/Documents/Sites/menu_back/node_modules/strapi-plugin-import-export-entries/server/utils/models.js:32:39)
    at updateOrCreate (/Users/charlesdoiron/Documents/Sites/menu_back/node_modules/strapi-plugin-import-export-entries/server/services/import/import.js:56:21)
    at /Users/charlesdoiron/Documents/Sites/menu_back/node_modules/strapi-plugin-import-export-entries/server/services/import/import.js:101:33
    at Array.map (<anonymous>)
    at updateOrCreateRelation (/Users/charlesdoiron/Documents/Sites/menu_back/node_modules/strapi-plugin-import-export-entries/server/services/import/import.js:101:15)
    at /Users/charlesdoiron/Documents/Sites/menu_back/node_modules/strapi-plugin-import-export-entries/server/services/import/import.js:58:28
    at Array.map (<anonymous>)
    at updateOrCreate (/Users/charlesdoiron/Documents/Sites/menu_back/node_modules/strapi-plugin-import-export-entries/server/services/import/import.js:57:41)
    at /Users/charlesdoiron/Documents/Sites/menu_back/node_modules/strapi-plugin-import-export-entries/server/services/import/import.js:32:18
    at catchError (/Users/charlesdoiron/Documents/Sites/menu_back/node_modules/strapi-plugin-import-export-entries/server/utils/index.js:19:11)
    at Object.importData (/Users/charlesdoiron/Documents/Sites/menu_back/node_modules/strapi-plugin-import-export-entries/server/services/import/import.js:31:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.importData (/Users/charlesdoiron/Documents/Sites/menu_back/node_modules/strapi-plugin-import-export-entries/server/controllers/import/import-data.js:13:15)
    at async returnBodyMiddleware (/Users/charlesdoiron/Documents/Sites/menu_back/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/charlesdoiron/Documents/Sites/menu_back/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /Users/charlesdoiron/Documents/Sites/menu_back/node_modules/@strapi/strapi/lib/middlewares/body.js:51:9`

The error came from here : 
https://github.com/Baboo7/strapi-plugin-import-export-entries/blob/9c289275621ca9e753d99519f2ff0b23022438b0/server/utils/models.js#L32

Here is the ContentType model with the dynamicZone:

https://github.com/Charlesdoiron/bigmamma/blob/9956d5748b8cb1afc2a36d364485c274ed3728cf/src/api/menu/content-types/menu/schema.json#L15

Here is the component model (in the dynamicZone)
https://github.com/Charlesdoiron/bigmamma/blob/main/src/components/categories/category.json

Here is the exported json of the ContentType.
https://github.com/Charlesdoiron/bigmamma/blob/main/giorgia.json

**Expected behavior**
Import contentType with dynamicZone and repeatable components.

**Screenshots**

![Capture d’écran 2022-06-29 à 13 41 48](https://user-images.githubusercontent.com/4417717/176428311-4eb2a83c-602b-47d7-ba4e-6d276176f01f.png)

Thanks a lot.

**Comment by Baboo7** [comment]
The data provided helps a lot!
I published version `1.6.2` that fixes the issue

**Comment by Charlesdoiron** [comment]
Tanks a lot !!!!
