### ISSUE TITLE
[BUG] Export button not working when 'Apply filters' is set

### ISSUE THREAD

**Issue by mattpfeffer** [Baboo7/strapi-plugin-import-export-entries#50]
**Describe the bug**
I've run into the following error using the export button in the Admin UI on a collection (list view):

```console
[2022-09-01 16:35:19.449] error: Attribute createdat not found on model api::collection-type.collection-type
Error: Attribute createdat not found on model api::collection-type.collection-type
    at /Users/matt/Projects/project-name/node_modules/@strapi/database/lib/query/helpers/order-by.js:36:15
    at Array.flatMap (<anonymous>)
    at Object.processOrderBy (/Users/matt/Projects/project-name/node_modules/@strapi/database/lib/query/helpers/order-by.js:31:36)
    at Object.processState (/Users/matt/Projects/project-name/node_modules/@strapi/database/lib/query/query-builder.js:234:31)
    at Object.getKnexQuery (/Users/matt/Projects/project-name/node_modules/@strapi/database/lib/query/query-builder.js:285:12)
    at Object.execute (/Users/matt/Projects/project-name/node_modules/@strapi/database/lib/query/query-builder.js:388:25)
    at Object.findMany (/Users/matt/Projects/project-name/node_modules/@strapi/database/lib/entity-manager.js:129:70)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.findMany (/Users/matt/Projects/project-name/node_modules/@strapi/strapi/lib/services/entity-service/index.js:306:20)
    at async Object.exportData (/Users/matt/Projects/project-name/node_modules/strapi-plugin-import-export-entries/server/controllers/admin/export-controller/export-controller.js:22:19)
    at async returnBodyMiddleware (/Users/matt/Projects/project-name/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/matt/Projects/project-name/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /Users/matt/Projects/project-name/node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
    at async /Users/matt/Projects/project-name/node_modules/@strapi/strapi/lib/middlewares/logger.js:25:5
    at async /Users/matt/Projects/project-name/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/Users/matt/Projects/project-name/node_modules/@koa/cors/index.js:95:16)
```
This occurs when 'Apply filters and sort to exported data' is selected. The following line seems to cause this by transforming 'createdAt' into 'createdat':

```js
// server/controllers/admin/export-controller/export-controller.js.  Line 47
const [attr, value] = (sortRaw?.split(':') || []).map((v) => v.toLowerCase());
```
I would just submit a pull request but I'm not sure what unintended side affects there would be. I assume the string to lower case is there for a good reason.

**To Reproduce**

1. Go to 'Content Manager'
2. Select a  collection type
3. Apply any filter to the view
4. Hit 'Export'
5. Select 'Apply filters and sort to exported data', leave everything else default
6. Click 'Fetch Data'

**Expected behavior**
To export data with the filters/sort enabled.

**Additional context**
Strapi Version: 4.3.6 (node v16.16.0)
Plugin Version: 1.13.0

**Comment by Baboo7** [comment]
Good catch! The reason `toLowerCase` values is to have the sorting order as strapi expects : `DESC` => `desc`. But it shouldn't apply to the field's name.

I plan on getting a feature out by today, I'll integrate the fix along the way

**Comment by Baboo7** [comment]
Version `1.14.1` is out with the fix applied 🩹

**Comment by mattpfeffer** [comment]
Fantastic, updated and confirmed it's working on one of my environments 👍🏻

**Comment by Baboo7** [comment]
Great 👍 I'm closing this issue
